### ISSUE TITLE
Vehicle Post Management

### ISSUE THREAD

**Issue by YashDoshi07** [aquatrix/Capstone-Project#10]
Users (sellers) can **create, update, or delete their vehicle posts** for the vehicles they want to sell

**Comment by aquatrix** [comment]
The database has been created, and all the data has been stored. However, due to time constraints, we were unable to implement some features that we wanted, such as a full dedicated page for the car listing.

**Comment by mtrigo-fol** [comment]
> The database has been created, and all the data has been stored. However, due to time constraints, we were unable to implement some features that we wanted, such as a full dedicated page for the car listing.

"due to time constraints" doesn't really apply here when you had 2 weeks in the Sprint and 80% of the code comes from [this single commit](https://github.com/aquatrix/Capstone-Project/commit/9e0d233336233773ded301529348286566c1cd01) from June 9 (the last day of the Sprint)
