### ISSUE TITLE
Notification Alert

### ISSUE THREAD

**Issue by aquatrix** [aquatrix/Capstone-Project#8]
User can get the **alert** (Price drop notification), when they have car or item on their wish list.

**Comment by mtrigo-fol** [comment]
You'll have to have 2 different videos to show this feature working.
From one perspective, the user changes the price they're asking for a car.
In the other, the user gets a notification.

**Comment by mtrigo-fol** [comment]
You need 2 videos for this

**Comment by YashDoshi07** [comment]
Firebase cloud messaging implementation was a little hard, so we cannot complete that in this Sprint.
